import { Link, useRouterState } from "@tanstack/react-router";
import { useEffect, useMemo, useState, type ReactNode } from "react";
import { Activity, BarChart3, Bell, Bot, CalendarDays, ChevronDown, CircleHelp, ClipboardCheck, Command, Contact, LayoutDashboard, Menu, MessageSquareText, Plug, Search, Settings, Sparkles, Users, Workflow, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { leads, tasks, money } from "@/lib/anveo-data";

const nav=[
 {to:"/",label:"Visão Geral",icon:LayoutDashboard},{to:"/crm",label:"CRM",icon:Activity},{to:"/leads",label:"Leads",icon:Contact},{to:"/conversas",label:"Conversas",icon:MessageSquareText},{to:"/tarefas",label:"Tarefas",icon:ClipboardCheck},{to:"/agenda",label:"Agenda",icon:CalendarDays},{to:"/automacoes",label:"Automações",icon:Workflow},{to:"/agentes-ia",label:"Agentes IA",icon:Bot},{to:"/analytics",label:"Analytics",icon:BarChart3},{to:"/relatorios",label:"Relatórios",icon:Command},{to:"/equipe",label:"Equipe",icon:Users},{to:"/integracoes",label:"Integrações",icon:Plug},{to:"/configuracoes",label:"Configurações",icon:Settings},
] as const;
export function AppShell({children}:{children:ReactNode}){
 const path=useRouterState({select:s=>s.location.pathname}); const [collapsed,setCollapsed]=useState(false); const [mobile,setMobile]=useState(false); const [search,setSearch]=useState(false); const [notifications,setNotifications]=useState(false);
 useEffect(()=>{const fn=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();setSearch(true)}if(e.key==="Escape"){setSearch(false);setNotifications(false);setMobile(false)}};addEventListener("keydown",fn);return()=>removeEventListener("keydown",fn)},[]);
 const current=nav.find(i=>i.to===path)?.label ?? "ANVEO HUB";
 return <div className="min-h-screen bg-background text-foreground">
  <aside className={`fixed inset-y-0 left-0 z-40 hidden border-r border-sidebar-border bg-sidebar transition-[width] duration-200 lg:flex lg:flex-col ${collapsed?"w-16":"w-60"}`}>
   <div className="flex h-16 items-center border-b border-sidebar-border px-4"><Link to="/" className="flex min-w-0 items-center gap-3"><span className="grid size-8 shrink-0 place-items-center rounded-md bg-primary text-sm font-bold text-primary-foreground">A</span>{!collapsed&&<div className="min-w-0"><div className="truncate font-bold">ANVEO <span className="text-primary">HUB</span></div><div className="text-[10px] uppercase text-muted-foreground">Revenue OS</div></div>}</Link></div>
   <nav className="scroll-thin flex-1 overflow-y-auto px-2 py-3">{nav.map(item=>{const Icon=item.icon;const active=path===item.to;return <Link key={item.to} to={item.to} title={collapsed?item.label:undefined} className={`mb-1 flex h-9 items-center gap-3 rounded-md px-2.5 text-sm transition-colors ${active?"bg-sidebar-accent text-sidebar-accent-foreground":"text-muted-foreground hover:bg-sidebar-accent/60 hover:text-foreground"}`}><Icon className={`size-4 shrink-0 ${active?"text-primary":""}`}/>{!collapsed&&<span className="truncate">{item.label}</span>}</Link>})}</nav>
   <div className="border-t border-sidebar-border p-2"><button className="flex h-9 w-full items-center gap-3 rounded-md px-2.5 text-sm text-muted-foreground hover:bg-sidebar-accent hover:text-foreground"><CircleHelp className="size-4"/>{!collapsed&&"Ajuda"}</button><button onClick={()=>setCollapsed(v=>!v)} className="mt-1 flex h-9 w-full items-center gap-3 rounded-md px-2.5 text-sm text-muted-foreground hover:bg-sidebar-accent hover:text-foreground"><Menu className="size-4"/>{!collapsed&&(collapsed?"Expandir":"Recolher menu")}</button></div>
  </aside>
  <div className={`min-h-screen transition-[padding] duration-200 ${collapsed?"lg:pl-16":"lg:pl-60"}`}>
   <header className="sticky top-0 z-30 grid h-16 grid-cols-[minmax(0,1fr)_auto] items-center gap-3 border-b border-border bg-background/95 px-4 backdrop-blur md:px-6">
    <div className="flex min-w-0 items-center gap-3"><Button variant="ghost" size="icon" className="lg:hidden" onClick={()=>setMobile(true)} aria-label="Abrir menu"><Menu className="size-5"/></Button><div className="min-w-0"><div className="truncate text-sm font-semibold">{current}</div><div className="hidden text-xs text-muted-foreground sm:block">Operação comercial em tempo real</div></div></div>
    <div className="flex shrink-0 items-center gap-2"><button onClick={()=>setSearch(true)} className="hidden h-9 w-56 items-center gap-2 rounded-md border border-input bg-surface px-3 text-sm text-muted-foreground transition hover:border-primary/50 md:flex"><Search className="size-4"/><span>Buscar no Hub...</span><kbd className="ml-auto rounded border border-border px-1.5 py-0.5 text-[10px]">⌘ K</kbd></button><Button variant="ghost" size="icon" className="md:hidden" onClick={()=>setSearch(true)} aria-label="Buscar"><Search className="size-5"/></Button><div className="relative"><Button variant="ghost" size="icon" onClick={()=>setNotifications(v=>!v)} aria-label="Notificações"><Bell className="size-5"/><span className="absolute right-2 top-2 size-1.5 rounded-full bg-primary"/></Button>{notifications&&<Notifications onClose={()=>setNotifications(false)}/>}</div><button className="hidden items-center gap-2 rounded-md border border-border px-2 py-1.5 text-left sm:flex"><span className="grid size-7 place-items-center rounded bg-secondary text-xs font-semibold">AL</span><span className="max-w-28 truncate text-xs font-medium">ANVEO Digital</span><ChevronDown className="size-3 text-muted-foreground"/></button></div>
   </header>
   <main className="page-enter min-h-[calc(100vh-4rem)] p-4 pb-24 md:p-6 lg:pb-6">{children}</main>
  </div>
  {mobile&&<div className="fixed inset-0 z-50 lg:hidden"><button className="absolute inset-0 bg-background/80 backdrop-blur-sm" onClick={()=>setMobile(false)} aria-label="Fechar menu"/><div className="absolute inset-y-0 left-0 w-[82%] max-w-72 border-r border-border bg-sidebar p-3 shadow-2xl"><div className="mb-4 flex items-center justify-between p-2"><b>ANVEO <span className="text-primary">HUB</span></b><Button variant="ghost" size="icon" onClick={()=>setMobile(false)}><X className="size-5"/></Button></div>{nav.map(item=>{const Icon=item.icon;return <Link key={item.to} to={item.to} onClick={()=>setMobile(false)} className={`mb-1 flex h-10 items-center gap-3 rounded-md px-3 text-sm ${path===item.to?"bg-sidebar-accent text-foreground":"text-muted-foreground"}`}><Icon className="size-4"/>{item.label}</Link>})}</div></div>}
  <nav className="fixed inset-x-0 bottom-0 z-30 grid h-17 grid-cols-5 border-t border-border bg-background/95 px-2 backdrop-blur lg:hidden">{nav.slice(0,4).map(item=>{const Icon=item.icon;return <Link key={item.to} to={item.to} className={`flex flex-col items-center justify-center gap-1 text-[10px] ${path===item.to?"text-primary":"text-muted-foreground"}`}><Icon className="size-5"/>{item.label}</Link>})}<button onClick={()=>setMobile(true)} className="flex flex-col items-center justify-center gap-1 text-[10px] text-muted-foreground"><Menu className="size-5"/>Mais</button></nav>
  {search&&<SearchPalette onClose={()=>setSearch(false)}/>} 
 </div>
}
function SearchPalette({onClose}:{onClose:()=>void}){const [q,setQ]=useState("");const results=useMemo(()=>leads.filter(l=>(l.name+l.company+l.stage).toLowerCase().includes(q.toLowerCase())).slice(0,5),[q]);return <div className="fixed inset-0 z-[60] bg-background/80 p-4 pt-[12vh] backdrop-blur-sm" onMouseDown={onClose}><div className="mx-auto max-w-xl overflow-hidden rounded-lg border border-border bg-popover shadow-2xl" onMouseDown={e=>e.stopPropagation()}><div className="flex items-center gap-3 border-b border-border px-4"><Search className="size-5 text-muted-foreground"/><input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar leads, empresas, oportunidades ou tarefas..." className="h-14 w-full bg-transparent text-sm outline-none placeholder:text-muted-foreground"/><kbd className="text-xs text-muted-foreground">ESC</kbd></div><div className="max-h-96 overflow-y-auto p-2"><p className="px-2 py-2 text-[10px] font-semibold uppercase text-muted-foreground">Resultados rápidos</p>{results.map(l=><Link key={l.id} to="/leads/$leadId" params={{leadId:l.id}} onClick={onClose} className="flex items-center gap-3 rounded-md p-3 hover:bg-accent"><span className="grid size-8 place-items-center rounded bg-secondary text-xs">{l.initials}</span><span className="min-w-0 flex-1"><b className="block truncate text-sm">{l.name}</b><span className="block truncate text-xs text-muted-foreground">{l.company} · {l.stage}</span></span><span className="text-xs text-muted-foreground">{money(l.value)}</span></Link>)}{tasks.filter(t=>t.title.toLowerCase().includes(q.toLowerCase())).slice(0,2).map(t=><Link key={t.title} to="/tarefas" onClick={onClose} className="flex items-center gap-3 rounded-md p-3 hover:bg-accent"><ClipboardCheck className="size-4 text-primary"/><span className="text-sm">{t.title}</span></Link>)}</div></div></div>}
function Notifications({onClose}:{onClose:()=>void}){return <div className="absolute right-0 top-11 w-[min(22rem,calc(100vw-2rem))] rounded-lg border border-border bg-popover p-2 shadow-2xl"><div className="flex items-center justify-between px-2 py-2"><b className="text-sm">Notificações</b><button onClick={onClose}><X className="size-4 text-muted-foreground"/></button></div>{["Novo lead recebido pelo WhatsApp","Tarefa atrasada: Renata Alves","Automação concluiu 28 ações","Venda fechada: Atlas Contábil"].map((n,i)=><div key={n} className="flex gap-3 rounded-md p-2.5 hover:bg-accent"><span className={`mt-1.5 size-2 shrink-0 rounded-full ${i<2?"bg-primary":"bg-muted-foreground"}`}/><div><p className="text-xs font-medium">{n}</p><span className="text-[11px] text-muted-foreground">{i?`${i+1}h atrás`:"Agora"}</span></div></div>)}</div>}
