import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { Pencil, Plus, Search, X } from "lucide-react";
import { PageHeader, Badge } from "@/components/anveo/page";
import { Button } from "@/components/ui/button";
import { currentUserId, db, formatDate, money, type ClienteRow } from "@/lib/crm-data";

export const Route = createFileRoute("/_authenticated/clientes")({ head: () => ({ meta: [{ title: "Clientes — ANVEO HUB" }] }), component: Clients });

function Clients() {
  const [rows, setRows] = useState<ClienteRow[]>([]);
  const [query, setQuery] = useState("");
  const [editing, setEditing] = useState<ClienteRow | null>(null);
  const [message, setMessage] = useState("");
  async function load() { const user_id = await currentUserId(); const result = await db.from("clientes").select("*").eq("user_id", user_id).order("created_at", { ascending: false }); if (result.error) throw result.error; setRows(result.data || []); }
  useEffect(() => { load().catch((error) => setMessage(error.message)); }, []);
  const visible = useMemo(() => rows.filter((row) => `${row.nome} ${row.empresa || ""} ${row.email || ""}`.toLowerCase().includes(query.toLowerCase())), [rows, query]);
  return <div className="mx-auto max-w-6xl"><PageHeader eyebrow="Base de clientes" title="Clientes" description={`${rows.length} cliente(s) cadastrados`} actions={<Button onClick={() => setEditing({ id: "", user_id: "", lead_id: null, nome: "", empresa: null, email: null, telefone: null, status: "ativo", valor_fechado: null, data_fechamento: null, created_at: "", updated_at: "" })}><Plus className="size-4" />Novo cliente</Button>} />{message && <p className="mb-4 rounded-md bg-destructive/10 p-3 text-sm text-destructive">{message}</p>}<section className="panel overflow-hidden"><div className="border-b border-border p-3"><label className="flex h-10 max-w-md items-center gap-2 rounded-md border border-input bg-background px-3"><Search className="size-4 text-muted-foreground" /><input value={query} onChange={(e) => setQuery(e.target.value)} className="w-full bg-transparent text-sm outline-none" placeholder="Buscar cliente, empresa ou e-mail" /></label></div>{visible.length === 0 ? <div className="flex min-h-52 items-center justify-center p-6 text-sm text-muted-foreground">Nenhum cliente encontrado.</div> : <div className="divide-y divide-border">{visible.map((row) => <div key={row.id} className="grid gap-3 p-4 md:grid-cols-[minmax(0,1fr)_auto_auto] md:items-center"><div><h3 className="text-sm font-semibold">{row.nome}</h3><p className="text-xs text-muted-foreground">{row.empresa || "Sem empresa"}{row.email ? ` · ${row.email}` : ""}</p></div><div className="text-left md:text-right"><Badge tone={row.status === "fechado" ? "green" : row.status === "inativo" ? "neutral" : "blue"}>{row.status}</Badge><p className="mt-1 text-xs text-muted-foreground">{row.data_fechamento ? formatDate(row.data_fechamento) : "Sem fechamento"} · {money(row.valor_fechado)}</p></div><Button variant="ghost" size="icon" onClick={() => setEditing(row)}><Pencil className="size-4" /></Button></div>)}</div>}</section>{editing && <ClientForm initial={editing} onClose={() => setEditing(null)} onSaved={() => { setEditing(null); load(); }} />}</div>;
}

function ClientForm({ initial, onClose, onSaved }: { initial: ClienteRow; onClose: () => void; onSaved: () => void }) { const [form, setForm] = useState<any>({ ...initial }); const [error, setError] = useState(""); const update = (key: string, value: string) => setForm((current: any) => ({ ...current, [key]: value })); async function save() { if (!form.nome) return setError("Nome é obrigatório."); const user_id = await currentUserId(); const payload = { user_id, nome: form.nome, empresa: form.empresa || null, email: form.email || null, telefone: form.telefone || null, status: form.status, valor_fechado: form.valor_fechado ? Number(form.valor_fechado) : null, data_fechamento: form.data_fechamento || null, lead_id: form.lead_id || null }; const result = form.id ? await db.from("clientes").update(payload).eq("id", form.id) : await db.from("clientes").insert(payload); if (result.error) return setError(result.error.message); onSaved(); } return <div className="fixed inset-0 z-50 grid place-items-center bg-background/75 p-4"><div className="w-full max-w-lg rounded-lg border border-border bg-popover p-5 shadow-2xl"><div className="flex items-center justify-between"><h2 className="font-semibold">{initial.id ? "Editar cliente" : "Novo cliente"}</h2><Button variant="ghost" size="icon" onClick={onClose}><X className="size-4" /></Button></div><div className="mt-4 grid gap-3"><input value={form.nome} onChange={(e) => update("nome", e.target.value)} className="h-10 rounded-md border border-input bg-surface px-3 text-sm" placeholder="Nome" /><input value={form.empresa || ""} onChange={(e) => update("empresa", e.target.value)} className="h-10 rounded-md border border-input bg-surface px-3 text-sm" placeholder="Empresa" /><input value={form.email || ""} onChange={(e) => update("email", e.target.value)} className="h-10 rounded-md border border-input bg-surface px-3 text-sm" placeholder="E-mail" /><input value={form.telefone || ""} onChange={(e) => update("telefone", e.target.value)} className="h-10 rounded-md border border-input bg-surface px-3 text-sm" placeholder="Telefone" /><div className="grid gap-3 sm:grid-cols-2"><select value={form.status} onChange={(e) => update("status", e.target.value)} className="h-10 rounded-md border border-input bg-surface px-3 text-sm"><option value="ativo">Ativo</option><option value="inativo">Inativo</option><option value="fechado">Fechado</option></select><input type="date" value={form.data_fechamento || ""} onChange={(e) => update("data_fechamento", e.target.value)} className="h-10 rounded-md border border-input bg-surface px-3 text-sm" /></div><input type="number" value={form.valor_fechado || ""} onChange={(e) => update("valor_fechado", e.target.value)} className="h-10 rounded-md border border-input bg-surface px-3 text-sm" placeholder="Valor fechado" />{error && <p className="text-xs text-destructive">{error}</p>}<Button onClick={save}>Salvar cliente</Button></div></div></div>; }
