import { createFileRoute } from "@tanstack/react-router";
import { ArrowDownRight, ArrowUpRight, Bot, CalendarClock, ChevronRight, CircleDollarSign, Clock3, MessageCircle, Sparkles, Target, TrendingUp, UserPlus, Users } from "lucide-react";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { activities, chartData, money } from "@/lib/anveo-data";
import { Badge, PageHeader } from "@/components/anveo/page";
import { Button } from "@/components/ui/button";

export const Route = createFileRoute("/")({
  head:()=>({meta:[{title:"Visão Geral — ANVEO HUB"},{name:"description",content:"Command Center da operação comercial."},{property:"og:title",content:"Visão Geral — ANVEO HUB"},{property:"og:description",content:"Command Center da operação comercial."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),
  component: Index,
});

// IMPORTANT: Replace this placeholder. See ./README.md for routing conventions.
function Index() {
 const metrics=[{label:"Leads hoje",value:"18",delta:"+12,5%",up:true,icon:UserPlus},{label:"Pipeline total",value:"R$ 486 mil",delta:"+8,2%",up:true,icon:TrendingUp},{label:"Vendas fechadas",value:"R$ 92,4 mil",delta:"+18,7%",up:true,icon:CircleDollarSign},{label:"Taxa de conversão",value:"24,8%",delta:"−1,4%",up:false,icon:Target}];
 return <div className="mx-auto max-w-[1600px]"><PageHeader eyebrow="Command Center" title="Bom dia, Lucas" description="Acompanhe o que exige atenção e onde sua operação está avançando." actions={<Button><Sparkles className="size-4"/>Resumo com IA</Button>}/>
 <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(m=>{const Icon=m.icon;return <article key={m.label} className="panel p-4"><div className="flex items-start justify-between"><span className="text-xs text-muted-foreground">{m.label}</span><Icon className="size-4 text-muted-foreground"/></div><div className="mt-3 flex items-end justify-between gap-2"><strong className="text-2xl font-semibold">{m.value}</strong><span className={`flex items-center text-xs ${m.up?"text-success":"text-destructive"}`}>{m.up?<ArrowUpRight className="size-3"/>:<ArrowDownRight className="size-3"/>}{m.delta}</span></div><p className="mt-1 text-[10px] text-muted-foreground">vs. período anterior</p></article>})}</section>
 <section className="mt-4 grid gap-4 xl:grid-cols-[minmax(0,1.7fr)_minmax(300px,.8fr)]"><article className="panel min-w-0 p-4"><div className="mb-4 flex items-center justify-between"><div><h2 className="text-sm font-semibold">Performance comercial</h2><p className="text-xs text-muted-foreground">Leads e vendas nos últimos 7 dias</p></div><Badge tone="green">+14,2%</Badge></div><div className="h-64"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chartData}><defs><linearGradient id="leadFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="var(--primary)" stopOpacity={.32}/><stop offset="100%" stopColor="var(--primary)" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="var(--border)" vertical={false}/><XAxis dataKey="name" stroke="var(--muted-foreground)" fontSize={11} tickLine={false} axisLine={false}/><YAxis stroke="var(--muted-foreground)" fontSize={11} tickLine={false} axisLine={false}/><Tooltip contentStyle={{background:"var(--popover)",border:"1px solid var(--border)",borderRadius:8,fontSize:12}}/><Area type="monotone" dataKey="leads" stroke="var(--primary)" strokeWidth={2} fill="url(#leadFill)"/><Area type="monotone" dataKey="vendas" stroke="var(--success)" strokeWidth={2} fill="transparent"/></AreaChart></ResponsiveContainer></div></article>
 <article className="panel p-4"><div className="mb-4 flex items-center gap-2"><Sparkles className="size-4 text-primary"/><h2 className="text-sm font-semibold">Insights da IA</h2></div><div className="space-y-3">{["Sua conversão aumentou 12% nesta semana.","Instagram está convertendo 1,8× melhor.","R$ 18.500 estão sem interação há 5 dias.","6 leads têm alta probabilidade de fechamento."].map((x,i)=><div key={x} className="border-l-2 border-primary/50 pl-3"><p className="text-xs leading-5">{x}</p>{i===2&&<button className="mt-1 text-[11px] text-primary">Ver oportunidades</button>}</div>)}</div></article></section>
 <section className="mt-4 grid gap-4 lg:grid-cols-2"><article className="panel p-4"><div className="mb-4 flex items-center justify-between"><div><h2 className="text-sm font-semibold">Prioridades de hoje</h2><p className="text-xs text-muted-foreground">Ordenadas por impacto comercial</p></div><CalendarClock className="size-4 text-muted-foreground"/></div>{[{n:5,t:"Leads sem resposta há mais de 24 horas",tone:"red" as const},{n:3,t:"Propostas aguardando retorno",tone:"amber" as const},{n:2,t:"Oportunidades próximas do fechamento",tone:"blue" as const},{n:7,t:"Tarefas vencendo hoje",tone:"neutral" as const}].map((p,i)=><button key={p.t} className="grid w-full grid-cols-[auto_minmax(0,1fr)_auto] items-center gap-3 border-t border-border py-3 text-left first:border-0"><span className="grid size-7 place-items-center rounded bg-secondary text-xs font-semibold">{p.n}</span><span className="truncate text-xs">{p.t}</span><ChevronRight className="size-4 text-muted-foreground"/></button>)}</article>
 <article className="panel p-4"><div className="mb-4 flex items-center justify-between"><div><h2 className="text-sm font-semibold">Pulso da operação</h2><p className="text-xs text-muted-foreground">Atividade recente da equipe</p></div><span className="flex items-center gap-1 text-[10px] text-success"><span className="size-1.5 rounded-full bg-success"/>Ao vivo</span></div>{activities.map((a,i)=><div key={a.title} className="grid grid-cols-[auto_minmax(0,1fr)_auto] gap-3 border-t border-border py-3 first:border-0"><span className="mt-0.5 grid size-7 place-items-center rounded bg-secondary">{i===0?<MessageCircle className="size-3.5 text-primary"/>:i===2?<Bot className="size-3.5 text-primary"/>:<Clock3 className="size-3.5 text-muted-foreground"/>}</span><div className="min-w-0"><p className="truncate text-xs font-medium">{a.title}</p><p className="truncate text-[11px] text-muted-foreground">{a.detail}</p></div><span className="text-[10px] text-muted-foreground">{a.time}</span></div>)}</article></section>
 <section className="mt-4 panel overflow-hidden"><div className="flex items-center justify-between border-b border-border p-4"><div><h2 className="text-sm font-semibold">Pipeline por etapa</h2><p className="text-xs text-muted-foreground">{money(486300)} em oportunidades abertas</p></div><Button variant="ghost" size="sm" asChild><a href="/crm">Abrir CRM <ChevronRight className="size-3"/></a></Button></div><div className="grid gap-px bg-border sm:grid-cols-5">{[["Novo lead",24,"R$ 54 mil"],["Contato",18,"R$ 72 mil"],["Qualificado",13,"R$ 108 mil"],["Proposta",9,"R$ 139 mil"],["Negociação",6,"R$ 113 mil"]].map(([s,n,v])=><div key={s} className="bg-surface p-4"><span className="text-[10px] uppercase text-muted-foreground">{s}</span><div className="mt-2 flex items-end justify-between"><b className="text-lg">{n}</b><span className="text-xs text-muted-foreground">{v}</span></div></div>)}</div></section></div>
}
